--- 
mediaPath: /media/a2fa7d4f-7d8e-4315-a565-1881d5e884b1/scotty
tempPath: /media/a2fa7d4f-7d8e-4315-a565-1881d5e884b1/scotty/video/qBT/temp_parts
mediaExt: .avi
playHistoryFile: /home/sacarlson/vlc_history.txt
